name: Main Build

on:
    push:
        branches: [ main ]

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'