name: Main Build

on:
    push:
        branches: [ main ]
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SEMVER: ${{ vars.SEMVER }}

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - uses: actions/checkout@v4
            - name: generate_tag
              run: |
                
                git config user.name "GitHub Actions"
                git config user.email "github-actions@users.noreply.github.com"
                CURRENT=$(git tag --list "${SEMVER}*" --sort=-version:refname | head -n 1)
                NEW_TAG=$(echo $CURRENT | python ./.ci/bump_v2.py 2>&1)
                echo "Generated new tag: $NEW_TAG"
                git tag $NEW_TAG
                git push origin tag $NEW_TAG
