ename: Main Build

on:
    push:
        branches: [ main ]
env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: AUTH
              if: env.GH_TOKEN == ''
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV
            - uses: actions/checkout@v4
              with:
                token: ${{ secrets.TOKEN }}
                ref: main
            - name: generate_tag
              run: |
                
                git config user.name "GitHub Actions"
                git config user.email "github-actions@users.noreply.github.com"

                NEW_TAG=$(python ./.ci/bump.py 2>&1)
                echo "Generated new tag: $NEW_TAG"

                git tag $NEW_TAG

                git add .

                git commit -m "$NEW_TAG [skip-ci]"
                git push
                #git push origin tag $NEW_TAG
                
                #gh pr create --title "TAG $NEW_TAG" --body "[skip-ci]" --head $(git branch --show-current) --base main
                #gh pr merge --auto --delete-branch "$NEW_TAG"
