name: Main Build

on:
    push:
        branches: [ main ]
env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - uses: actions/checkout@v3
            - name: generate_tag
              run: |
                
                git config user.name "GitHub Actions"
                git config user.email "github-actions@users.noreply.github.com"
                NEW_TAG=$(python ./.ci/getversion.py false 2>&1)
                git branch $NEW_TAG
                git switch $NEW_TAG

                NEW_TAG=$(python ./.ci/bump.py 2>&1)
                echo "Generated new tag: $NEW_TAG"

                git tag $NEW_TAG

                git add .

                git commit -m "$NEW_TAG [skip-ci]"
                git push --set-upstream origin $NEW_TAG
                git push
                #git push origin tag $NEW_TAG
                
                gh pr create --title "TAG $NEW_TAG" --body "[skip-ci]" --head $(git branch --show-current) --base main
                #gh pr merge --auto --delete-branch "$NEW_TAG"
